on:
  push:
    tags:
      - 'v*.*'
# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npx webpack
      - name: Pack
        run: |
          zip -r ext.zip manifest.json scripts popup icon
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ext.zip
          asset_name: ext
          tag: ${{ github.ref_name }}
          overwrite: true
          body: "New release"
          
        
