on:
  push:
    branches:
      - 'main'
# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npx webpack
      - name: Pack
        run: |
          zip -r ext.zip manifest.json scripts popup icon
          gh release upload ${{github.event.release.tag_name}} ext.zip
          rm -fdr ext.zip
          
        
